// Categories
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORIES_INFO = 'FETCH_CATEGORIES_INFO'
export const CREATE_CATEGORIES = 'CREATE_CATEGORIES'
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'
export const RESET_CATEGORIES_FORM = 'RESET_CATEGORIES_FORM'
export const CATEGORY_FORM_SUBMIT_SUCCESS = 'CATEGORY_FORM_SUBMIT_SUCCESS'

//PortalContents
export const FETCH_HERO_BANNERS = 'FETCH_HERO_BANNERS'
export const GET_PRODUCT_BANNER_LIST = 'GET_PRODUCT_BANNER_LIST'